# Generated by Django 5.0.7 on 2024-08-23 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DriveAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RepairMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SteerableAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineSerialNumber', models.TextField(unique=True)),
                ('engineNumber', models.TextField(unique=True)),
                ('transmissionNumber', models.TextField(unique=True)),
                ('driveAxleNumber', models.TextField(unique=True)),
                ('steerableAxleNumber', models.TextField(unique=True)),
                ('deliveryContractNumber', models.TextField()),
                ('shipmentDate', models.DateField()),
                ('consignee', models.TextField()),
                ('deliveryAddress', models.TextField()),
                ('equipment', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.clients')),
                ('driveAxleModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.driveaxlemodel')),
                ('engineModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.enginemodel')),
                ('machineModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.machinemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.role')),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.role'),
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.role')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenanceDate', models.DateField()),
                ('motorResource', models.IntegerField()),
                ('workOrderNumber', models.TextField(max_length=64)),
                ('workOrderDate', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.machine')),
                ('maintenanceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.maintenancetype')),
                ('organMaintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.organmaintenance')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.servicecompany')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.servicecompany'),
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failureDate', models.DateField()),
                ('operatingTime', models.IntegerField()),
                ('failureDescription', models.TextField()),
                ('usedSpareParts', models.TextField()),
                ('repairDate', models.DateField()),
                ('equipmentDowntime', models.IntegerField()),
                ('failureNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.failurenode')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.machine')),
                ('repairMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.repairmethod')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.servicecompany')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='steerableAxleModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.steerableaxlemodel'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmissionModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.transmissionmodel'),
        ),
    ]
