# Generated by Django 5.0.7 on 2024-08-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='driveAxleNumber',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engineNumber',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machineSerialNumber',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steerableAxleNumber',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmissionNumber',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='workOrderNumber',
            field=models.TextField(max_length=64),
        ),
    ]
